### ISSUE TITLE
lockfree on armv7, bus error (core dumped)

### ISSUE THREAD

**Issue by Jackarain** [boostorg/lockfree#11]
```c++
# root at alarmpi in ~ [21:36:15]
$ cat test.cpp
#include <atomic>
#include <boost/lockfree/queue.hpp>
#include <iostream>

std::atomic_int intcount;
boost::lockfree::queue<int> intpool(100);

int main()
{
        return 0;
}





# root at alarmpi in ~ [21:36:53]
$ g++ test.cpp -std=c++11





# root at alarmpi in ~ [21:37:15]
$ ./a.out
[1]    31406 bus error (core dumped)  ./a.out





# root at alarmpi in ~ [21:37:27]
$ coredumpctl gdb 31406
           PID: 31406 (a.out)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 7 (BUS)
     Timestamp: 一 2015-04-27 21:37:27 CST (12s ago)
  Command Line: ./a.out
    Executable: /root/a.out
 Control Group: /user.slice/user-0.slice/session-c6.scope
          Unit: session-c6.scope
         Slice: user-0.slice
       Session: c6
     Owner UID: 0 (root)
       Boot ID: f2ff2834fe86475d8008560472158aa9
    Machine ID: 20d4f52b53de4dd9aa7ac72e93285b0a
      Hostname: alarmpi
      Coredump: /var/lib/systemd/coredump/core.a\x2eout.0.f2ff2834fe86475d8008560472158aa9.31406.1430141847000000.lz4
       Message: Process 31406 (a.out) of user 0 dumped core.

GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "armv7l-unknown-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/a.out...(no debugging symbols found)...done.
[New LWP 31406]
Core was generated by `./a.out'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00010ec8 in std::atomic<boost::lockfree::detail::tagged_ptr<boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node, std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> >::freelist_node> >::load(std::memory_order) const ()
(gdb) bt
#0  0x00010ec8 in std::atomic<boost::lockfree::detail::tagged_ptr<boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node, std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> >::freelist_node> >::load(std::memory_order) const ()
#1  0x0001110c in boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node, std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> >::deallocate_impl_unsafe(boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node*) ()
#2  0x00010e94 in void boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node, std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> >::deallocate<false>(boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node*) ()
#3  0x00010bd0 in boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node, std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> >::freelist_stack<std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> >(std::allocator<boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::node> const&, unsigned int) ()
#4  0x00010a34 in boost::lockfree::queue<int, boost::parameter::void_, boost::parameter::void_, boost::parameter::void_>::queue(unsigned int) ()
#5  0x000107e8 in __static_initialization_and_destruction_0(int, int) ()
#6  0x00010820 in _GLOBAL__sub_I_intcount ()
#7  0x000119f4 in __libc_csu_init ()
#8  0x76c22ccc in __libc_start_main () from /usr/lib/libc.so.6
#9  0x0001065c in _start ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) q






# root at alarmpi in ~ [21:37:47]
$ uname -a
Linux alarmpi 3.18.11-4-ARCH #1 SMP PREEMPT Tue Apr 21 21:52:58 MDT 2015 armv7l GNU/Linux





# root at alarmpi in ~ [21:37:50]
$ g++ -v
使用内建 specs。
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/armv7l-unknown-linux-gnueabihf/4.9.2/lto-wrapper
目标：armv7l-unknown-linux-gnueabihf
配置为：/build/gcc/src/gcc-4.9-20150304/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-cloog-backend=isl --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --disable-multilib --disable-werror --enable-checking=release --host=armv7l-unknown-linux-gnueabihf --build=armv7l-unknown-linux-gnueabihf --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16
线程模型：posix
gcc 版本 4.9.2 20150304 (prerelease) (GCC)

# root at alarmpi in ~ [21:37:58]
$ /lib/libc-2.21.so
GNU C Library (GNU libc) stable release version 2.21, by Roland McGrath et al.
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.9.2 20150304 (prerelease).
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, please see:
<https://github.com/archlinuxarm/PKGBUILDs/issues>.
```

**Comment by polaris** [comment]
I can reproduce this on an Android device by executing the line

    boost::lockfree::queue<int> intpool(100);

in a native module called via JNI.

**Comment by polaris** [comment]
It does not crash for me when using Boost.Atomic instead of std::atomic.

**Comment by Jackarain** [comment]
@polaris try upgrade gcc to 5.3

**Comment by zyv** [comment]
I'm curious as to whether this problem is related to another issue that I have recently reported or not?

https://svn.boost.org/trac/boost/ticket/11968

Could you please try removing `BOOST_LOCKFREE_CACHELINE_ALIGNMENT` from `queue.hpp`:

```
struct BOOST_LOCKFREE_CACHELINE_ALIGNMENT node { ... };
```

and see whether the test program segfaults or not?

Also, since you are using GCC 5.3, you do have fresh sanitizers at hand. It would be interesting to see the results if you compile with `-fsanitize=address -fsanitize=undefined` and run the resulting executable.

**Comment by biddisco** [comment]
I had problems with boost.lockfree on Raspberry Pi 2 and found this thread.
In my case using 
#define BOOST_LOCKFREE_NO_HDR_ATOMIC 
in lockfree/detail/atomic.hpp solves the bus error (as noted above).
I will test the BOOST_LOCKFREE_CACHELINE_ALIGNMENT suggestion this evening when I have access to the Pi.

**Comment by polaris** [comment]
@biddisco I can confirm that using BOOST_LOCKFREE_NO_HDR_ATOMIC solves the bus error.

**Comment by timblechmann** [comment]
@biddisco or @polaris: could you try to tweak https://github.com/boostorg/lockfree/blob/develop/include/boost/lockfree/detail/atomic.hpp#L22 so that it won't use std::atomic on arm?

**Comment by polaris** [comment]
I can not reproduce this with Boost 1.60 and GCC 5.2 on a Pi 2. I'll with an Android device asap.

**Comment by biddisco** [comment]
I tried a few tests. 

1. Removing `BOOST_LOCKFREE_CACHELINE_ALIGNMENT` from 
```
struct BOOST_LOCKFREE_CACHELINE_ALIGNMENT node { ... };
```
didn't help.

2. Changing the alignment by setting 
```
#if defined(__arm__) && defined (__GNUC__)
    #define BOOST_LOCKFREE_CACHELINE_BYTES 32
#else
    #define BOOST_LOCKFREE_CACHELINE_BYTES 64
#endif
```
in boost/lockfree/detail/prefix.hpp. According to the armv7 docs, 32 should be ok, but I tried 8,16,32 and all gave the bus error.

3. So I went back to the suggestion of @polaris and changed boost/lockfree/detail/atomic.hpp 
```
// GCC supports atomic<> from version 4.8 onwards.
// but armv7 gives 'bus error' when using lockfree+std::atomic
#if (BOOST_GCC >= 40800) && (__cplusplus >= 201103L) && !defined(__arm__)
#undef BOOST_LOCKFREE_NO_HDR_ATOMIC
#endif
```

However, I double checked the preprocessor architecture flags being set by the compiler and now see that my gcc-4.9.1 cross compiler for OSX is defining ```gcc -dM -E - < /dev/null | grep ARM```
```
#define __ARM_SIZEOF_WCHAR_T 32
#define __ARM_FEATURE_SAT 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARMEL__ 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 12
#define __ARM_NEON_FP 4
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_PCS_VFP 1
#define __ARM_FEATURE_LDREX 4
#define __ARM_FEATURE_QBIT 1
#define __ARM_ARCH_6__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_ARCH_ISA_THUMB 1
#define __ARM_ARCH 6
#define __ARM_FEATURE_SIMD32 1
#define __ARM_EABI__ 1
#define __ARM_FEATURE_DSP 1
```
which is for arm6 and not arm7, so I can't be sure if the code is being correctly generated for arm7 regarding things like the cache alignment. Using the boost::atomic seems like the best/safest option for my needs right now. Once I get a new cross compiler built for arm7, I'll revist the problem.

**Comment by zyv** [comment]
@polaris @biddisco could you please retry with the latest master of lockfree? My suspicion is that commit 72548c26e5243c88660e8c24524616dff3f18164 (and several preceding ones concerning the alignment of nodes) should fix the issue, at least they fixed it for me on x86.

I believe that using Boost.Atomic doesn't really solve the problem, but rather masks it; the nodes still remain wrongly aligned, but it seems that Boost.Atomic implementation is somehow able to access them without provoking a SIGBUS.

The latest changes seem to have finally fixed the alignment issues, however, and thus I would hope that the problem is solved for good.

**Comment by LucHermitte** [comment]
Hi

I can't say what I observe is related to the crash observed. However, it seems to be in the continuation of some other messages. Let me know if you prefer to open another issue.

As @zyv suggested, I've compiled the initial example (with `intpool.push(0);` added, in order to trick the compiler to not optimize the variable away), with `$CXXFLAGS` set to: `-std=c++14  -g -O2 -fsanitize=address,undefined -fno-omit-frame-pointer` and I see the following:

```
~/local/boost/1_63_0-san14/include/boost/lockfree/detail/freelist.hpp:102:13: runtime error: constructor call on misaligned address 0x60600000caa0 for type 'struct node', which requires 64 byte alignment
0x60600000caa0: note: pointer points here
 01 00 80 7b  00 cb 00 00 60 60 be be  be be be be be be be be  be be be be be be be be  be be be be
              ^ 
    #0 0x4032f3 in boost::lockfree::queue<int*>::node* boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int*>::node, std::allocator<boost::lockfree::queue<int*>::node> >::construct<true, false, int*, boost::lockfree::queue<int*>::node*>(int* const&, boost::lockfree::queue<int*>::node* const&) ~/local/boost/1_63_0-san14/include/boost/lockfree/detail/freelist.hpp:102
    #1 0x4032f3 in bool boost::lockfree::queue<int*>::do_push<false>(int* const&) ~/local/boost/1_63_0-san14/include/boost/lockfree/queue.hpp:293
    #2 0x400fcb in boost::lockfree::queue<int*>::push(int* const&) ~/local/boost/1_63_0-san14/include/boost/lockfree/queue.hpp:271
    #3 0x400fcb in main ~/dev/C++/tests/lock-free.cpp:11
    #4 0x7f4c140ff82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #5 0x4013d8 in _start (~/dev/C++/tests/lock-free+0x4013d8)

~/local/boost/1_63_0-san14/include/boost/lockfree/queue.hpp:111:19: runtime error: member access within misaligned address 0x60600000caa0 for type 'struct node', which requires 64 byte alignment
0x60600000caa0: note: pointer points here
 01 00 80 7b  00 cb 00 00 60 60 be be  be be be be be be be be  be be be be be be be be  be be be be
              ^ 
    #0 0x40310e in boost::lockfree::queue<int*>::node::node(int* const&, boost::lockfree::queue<int*>::node*) ~/local/boost/1_63_0-san14/include/boost/lockfree/queue.hpp:111
    #1 0x40310e in boost::lockfree::queue<int*>::node* boost::lockfree::detail::freelist_stack<boost::lockfree::queue<int*>::node, std::allocator<boost::lockfree::queue<int*>::node> >::construct<true, false, int*, boost::lockfree::queue<int*>::node*>(int* const&, boost::lockfree::queue<int*>::node* const&) ~/local/boost/1_63_0-san14/include/boost/lockfree/detail/freelist.hpp:102
    #2 0x40310e in bool boost::lockfree::queue<int*>::do_push<false>(int* const&) ~/local/boost/1_63_0-san14/include/boost/lockfree/queue.hpp:293
    #3 0x400fcb in boost::lockfree::queue<int*>::push(int* const&) ~/local/boost/1_63_0-san14/include/boost/lockfree/queue.hpp:271
    #4 0x400fcb in main ~/dev/C++/tests/lock-free.cpp:11
    #5 0x7f4c140ff82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x4013d8 in _start (~/dev/C++/tests/lock-free+0x4013d8)
```
The context is:

 * boost 1.63.0, 
 * gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4), 
 * on a x86_64-linux-gnu

I have similar results with clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final).

**Comment by LucHermitte** [comment]
Continuing on my investigations, I've modified `select_freelist::type` to use boost aligned allocator instead of the default one.

```c++
    typedef typename mpl::if_c<IsCompileTimeSized || IsFixedSize,
                               fixed_size_freelist<T, fixed_sized_storage_type>,
                               freelist_stack<T, boost::alignment::aligned_allocator_adaptor<Alloc, BOOST_LOCKFREE_CACHELINE_BYTES > >
                              >::type type;
```

It seems to fix random deadlocks and crashes I had in [HPX ](https://github.com/STEllAR-GROUP/hpx) 1d_stencil_8 example.

I'm not sure this is the right correction though, I lack perspective on this topic.

**Comment by zyv** [comment]
I think it should fix the problem for the case when the nodes are allocated on the heap and this is exactly what I suggested in my bug report on Trac referenced above, but the problem with compile-time sized storage will, of course, remain, and also if you happen to pass your own allocators, you are back to square one, because they don't know how they should align the data, unless you make `BOOST_LOCKFREE_CACHELINE_BYTES` public.

To be honest, I was quite demotivated by lack of attention to my initial report, which seems to me a very severe problem, and luckily these days I don't have much to do with C++ anyways, so... good luck!

**Comment by timblechmann** [comment]
@zyv i'm not using arm, so the best way to get this issue fixed is to submit a PR ;)

**Comment by LucHermitte** [comment]
@timblechmann There is also the issue that the default allocator for the queue is using an `std::allocator` which doesn't  return aligned memory blocks. This issue is easy to check with the undefined sanitizer of clang and gcc. As I said, I can open a new issue if you prefer. Still I think this could be related to the current issue.

What I don't know is how the `queue` type is expected to be used. Either we say that `select_freelist::type` points to `aligned_allocator_adaptor<Alloc...` instead of `Alloc` in the case of dynamic sizes. But will this prevent the end-user to inject another (aligned) allocator of his own? Shall we say instead that the default allocator to be used isn't `std::allocator` but `aligned_allocator_adaptor<std::allocator...`? 
This is something I can't tell. I can't hardly emit a PR.

@zyv Thanks. Indeed, the fix may not be trivial as there seems to be interface issues.

**Comment by biddisco** [comment]
@LucHermitte I am a little busy for the next week or so, but I'll try to make some time to have a look at this. Since you mention that you had problems with one of the HPX tests/examples and I'm involved in that project, I'll try to reproduce your problem with the stencil test and then investigate more.

**Comment by zyv** [comment]
@timblechmann the problem that I reported has nothing to do with ARM per se. The code is just as wrong on x86 as on any other arch, only on x86 it doesn't crash in most of the cases, because unaligned access doesn't cause a #GP (by default), unless one uses unaligned versions of SIMD instructions.

**Comment by LucHermitte** [comment]
@biddisco The fix I have made helped me execute the 1d_sencil8 example with sanitization activated. But I still have crashes in release mode, and valgrind still sees many corruptions in debug mode.
Just to say that my fix improves things a little bit (sanitization is happy), but there are other problems.

**Comment by biddisco** [comment]
Is this on armv7 only - or other platforms too?

**Comment by LucHermitte** [comment]
@biddisco On other platforms. I gave shorten specifications in my first message ( x86_64-linux-gnu, ubuntu, gcc 5.4.0, boost 1.63.0). I've used this Issue as what was described by @zyv was extremely similar to what I experiment with sanitization.

**Comment by timblechmann** [comment]
well, alignment is mainly done to avoid false sharing, not to ensure correctness.
as for the queue, the scott/michael queue copies data from the node before checking if the data is valid (the reason why it requires trivial assignment. it would not totally surprise me, if it confuses the sanitiser ... also, the node data is interpreted differently when the node is on the freelist stack ...
